name: cup_companion
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.1
  cloud_firestore: ^5.4.1
  emoji_picker_flutter: ^3.0.0
  image_picker: ^1.1.2
  intl: any
  flutter_svg: ^1.1.6
  shared_preferences: ^2.3.2
  flutter_config: ^2.0.2
  firebase_storage: ^12.3.0
  firebase_core: ^3.4.1
  firebase_auth: ^5.2.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  firebase_database: ^11.1.2
  geolocator: ^13.0.1
  flutter_staggered_animations: ^1.0.0
  salomon_bottom_bar: ^3.3.1
  google_fonts: ^4.0.3
  geocoding: ^3.0.0
  path_provider: ^2.1.4
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.0.0-nullsafety.0
  google_maps_flutter: ^2.1.1
  location: ^4.4.0
  uuid: ^4.5.0
  flutter_dotenv: ^5.0.2
  http: ^0.13.5
  file_picker: ^8.1.2
  csv: ^6.0.0
  flutter_typeahead: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.4.12
  analyzer: ^6.4.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true # Enables code generation for localization

  assets:
    - assets/images/logo.png
    - assets/images/cappuccino_oat.png
    - assets/images/cappuccino.png
    - assets/images/default_avatar.png
    - assets/images/margarita.jpg
    - assets/images/green_tea.jpg
    - assets/images/espresso.jpg
    - assets/images/craft_beer.jpg
    - assets/illustrations/signup_illustration.svg
    - assets/illustrations/bottom_decor.svg
    - assets/illustrations/signin_illustration.svg
    - assets/illustrations/forgot_password_illustration.svg
    - assets/images/mug.jpg
    - assets/images/tshirt.jpg
    - assets/images/backpack.jpg
    - assets/images/headphones.jpg

  fonts:
    - family: Montserrat
      fonts:
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Regular.ttf