// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';


// ...



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_MglMu-1oRrIPHDyhulXZtPgAZB4pcLA',
    appId: '1:765764181076:web:f147ade3a92bc9190f21c1',
    messagingSenderId: '765764181076',
    projectId: 'cup-companion',
    authDomain: 'cup-companion.firebaseapp.com',
    databaseURL: 'https://cup-companion-default-rtdb.firebaseio.com',
    storageBucket: 'cup-companion.appspot.com',
    measurementId: 'G-SVF4EWWFYC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_MglMu-1oRrIPHDyhulXZtPgAZB4pcLA',
    appId: '1:765764181076:android:d7e02caff36dcfbb0f21c1',
    messagingSenderId: '765764181076',
    projectId: 'cup-companion',
    databaseURL: 'https://cup-companion-default-rtdb.firebaseio.com',
    storageBucket: 'cup-companion.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_MglMu-1oRrIPHDyhulXZtPgAZB4pcLA',
    appId: '1:765764181076:ios:7ac2bc09ba8a76de0f21c1',
    messagingSenderId: '765764181076',
    projectId: 'cup-companion',
    databaseURL: 'https://cup-companion-default-rtdb.firebaseio.com',
    storageBucket: 'cup-companion.appspot.com',
    iosBundleId: 'com.example.cupCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFSbixM17-Ley9x1OincQoWSiUPBBJpyg',
    appId: '1:765764181076:ios:7ac2bc09ba8a76de0f21c1',
    messagingSenderId: '765764181076',
    projectId: 'cup-companion',
    databaseURL: 'https://cup-companion-default-rtdb.firebaseio.com',
    storageBucket: 'cup-companion.appspot.com',
    iosBundleId: 'com.example.cupCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl_0uM5fLa4zdc-yca-oO7VVTVOhTRlBU',
    appId: '1:765764181076:web:40e23cd68c7d1f3b0f21c1',
    messagingSenderId: '765764181076',
    projectId: 'cup-companion',
    authDomain: 'cup-companion.firebaseapp.com',
    databaseURL: 'https://cup-companion-default-rtdb.firebaseio.com',
    storageBucket: 'cup-companion.appspot.com',
    measurementId: 'G-11K7JBS89J',
  );
}
